### ISSUE TITLE
About the picture

### ISSUE THREAD

**Issue by LeslieZhoa** [TropComplique/FaceBoxes-tensorflow#25]
https://github.com/TropComplique/FaceBoxes-tensorflow/blob/0dde35eda1cb3dab6586b94c583029162ec37aa5/create_tfrecords.py#L70
Hi @TropComplique  why did you only use the jpg to make records?

**Comment by TropComplique** [comment]
I believe that almost 100% of all images in WIDER dataset are `jpeg`.
So this line is not important.

**Comment by LeslieZhoa** [comment]
Thank you !
